name: blockchain_file_app
description: A beautiful Flutter app for uploading files to a free service and storing hashes locally.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.7
  crypto: ^3.0.2
  qr_flutter: ^4.0.0
  pdf: ^3.6.0
  printing: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  http: ^1.2.2 
  flutter_staggered_animations: ^1.0.0
  google_fonts: ^6.2.1  
  shimmer: ^2.0.0
  dio: ^5.7.0
  open_filex: ^4.4.0
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  awesome_notifications: ^0.10.1
  firebase_storage: ^13.0.5
  encrypt: ^5.0.3
  local_auth: ^3.0.0
  permission_handler: ^12.0.1
  uuid: ^4.5.2
  pdfx: ^2.9.2
  share_plus: ^12.0.1
  fluttertoast: ^9.0.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  connectivity_plus: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

  
flutter:
  uses-material-design: true
  assets:
      - assets/fonts/
  fonts:
      - family: Vazirmatn
        fonts:
          - asset: assets/fonts/Vazirmatn-Regular.ttf
          - asset: assets/fonts/Vazirmatn-Bold.ttf
            weight: 700